# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('cid', models.CharField(default='null', max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_year', models.CharField(default='2016-2017', max_length=50)),
                ('course_id', models.CharField(default='null', max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(blank=True, default=3, null=True)),
                ('attempts', models.CharField(default='Limited to 2 Attempts', max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=350, null=True)),
                ('prerequisite', models.CharField(blank=True, db_column='Prerequisite', max_length=50, null=True)),
                ('corequisite', models.CharField(blank=True, db_column='Corequisite', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=100, null=True)),
                ('schedule_type', models.CharField(blank=True, db_column='Schedule_Type', max_length=100, null=True)),
                ('hours_of_lect_perweek', models.IntegerField(blank=True, default=3, null=True)),
                ('hours_of_lab_perweek', models.IntegerField(blank=True, default=0, null=True)),
                ('grading', models.CharField(blank=True, db_column='Grading', max_length=50, null=True)),
                ('when_offer', models.CharField(default='See GMU Catalog', max_length=50)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(0.0, 'S = Satisfactory/No Credit'), (4.0, 'A+ = 4.0'), (4.0, 'A = 4.0'), (3.67, 'A- = 3.67'), (3.33, 'B+ = 3.33'), (3.0, 'B = 3.00'), (2.67, 'B- = 2.67'), (2.33, 'C+ = 2.33'), (2.0, 'C = 2.00'), (1.67, 'C- = 1.67'), (1.0, 'D = 1.00'), (0.0, 'F = 0.00')], default='A+ = 4.0')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=6)),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2016)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeplan.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeplan.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=6)),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2016)),
                ('sem_year', models.CharField(max_length=15, null=True)),
                ('predicted_grade', models.FloatField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeplan.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('program_of_study', models.CharField(choices=[('BIO_ENG', 'Bioengineering, BS'), ('APPLIED_CS', 'Applied Computer Science, BS'), ('COMPUTER_SCIENCE_BS', 'Computer Science, BS'), ('COMPUTER_ENGINEERING_BS', 'Computer Engineering, BS')], default='Computer Science, BS', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='interest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([('student', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together=set([('student', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('student', 'course_id')]),
        ),
    ]
