# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degreeplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmu_cs_course_topic_association',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField(db_column='topic_id', default=0)),
                ('result_set_id', models.IntegerField(db_column='result_set_id', default=0)),
                ('proportion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gmu_cs_course_topic_association',
            },
        ),
        migrations.CreateModel(
            name='gmu_cs_courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('title', models.CharField(blank=True, db_column='title', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=350, null=True)),
                ('description_raw', models.CharField(blank=True, db_column='description_raw', max_length=350, null=True)),
            ],
            options={
                'db_table': 'gmu_cs_courses',
            },
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('iterations', models.FloatField(blank=True, null=True)),
                ('num_topics', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result_set',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField(default=0)),
                ('words', models.CharField(blank=True, db_column='words', max_length=350, null=True)),
                ('result_set_id', models.ForeignKey(db_column='result_set_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='degreeplan.ResultSet')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='gmu_cs_course_topic_association',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default='0', on_delete=django.db.models.deletion.CASCADE, to='degreeplan.gmu_cs_courses'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('topic_id', 'result_set_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='gmu_cs_course_topic_association',
            unique_together=set([('course_id', 'topic_id', 'result_set_id')]),
        ),
    ]
