# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degreeplan', '0002_auto_20160824_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmu_cs_courses',
            name='description_raw',
        ),
    ]
