# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreeplan', '0003_remove_gmu_cs_courses_description_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGmuCourses',
            fields=[
                ('cid', models.CharField(default='null', max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('catalog_year', models.CharField(default='2016-2017', max_length=50)),
                ('course_id', models.CharField(default='null', max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(blank=True, default=3, null=True)),
                ('attempts', models.CharField(default='Limited to 2 Attempts', max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=350, null=True)),
                ('prerequisite', models.CharField(blank=True, db_column='Prerequisite', max_length=50, null=True)),
                ('schedule_type', models.CharField(blank=True, db_column='Schedule_Type', max_length=100, null=True)),
                ('hours_of_lect_perweek', models.IntegerField(blank=True, default=3, null=True)),
                ('hours_of_lab_perweek', models.IntegerField(blank=True, default=0, null=True)),
                ('when_offer', models.CharField(default='See GMU Catalog', max_length=50)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=100, null=True)),
                ('grading', models.CharField(blank=True, db_column='Grading', max_length=50, null=True)),
                ('corequisite', models.CharField(blank=True, db_column='Corequisite', max_length=50, null=True)),
            ],
            options={
                'db_table': 'all_courses',
            },
        ),
    ]
