# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('degreeplan', '0004_allgmucourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(choices=[(0.0, 'S = Satisfactory/No Credit'), (4.0, 'A+ = 4.0'), (4.0, 'A = 4.0'), (3.67, 'A- = 3.67'), (3.33, 'B+ = 3.33'), (3.0, 'B = 3.00'), (2.67, 'B- = 2.67'), (2.33, 'C+ = 2.33'), (2.0, 'C = 2.00'), (1.67, 'C- = 1.67'), (1.0, 'D = 1.00'), (0.0, 'F = 0.00')], default='A+ = 4.0')),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=6)),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2016)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeplan.AllGmuCourses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set([('student', 'course_id')]),
        ),
    ]
