# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degreeplan', '0005_auto_20160825_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='related_topics',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
