# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degreeplan', '0007_auto_20160907_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeplan.csbs_course'),
        ),
    ]
